title: 'iSchool Review'
author:
  name: 'iSchool Review'
  email: ischoolreview@ischool.berkeley.edu
taxonomies:
  - category
  - tag
  - author
metadata:
  description: 'An online publication showcasing the best information-centric work from professional graduate programs worldwide'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
visualization:
  d3js: true
  topojson: false
logo: user/images/isrlogo-wide.png
